### ISSUE TITLE
RSpec Error with react-rails

### ISSUE THREAD

**Issue by BorisBresciani** [reactjs/react-rails#1044]
Hello, I have an error that appears when I use RSpec.

### Steps to reproduce

Install rspec gem and factory bot gem:
```
group :test do
  gem 'rspec-rails'

 gem 'factory_bot_rails'
end
```

File: spec/controllers/occupations_controller_spec.rb:
```
require 'rails_helper'

RSpec.describe OccupationsController, type: :controller do
  describe 'GET #show' do
    it 'returns a success response' do
      occupation = create(:occupation)
      get :show, params: { slug: occupation.to_param }
      expect(response).to be_successful
    end
  end
end
```

Excute rspec:
`rspec`

Error appears:

 ```
 1) OccupationsController GET #show returns a success response
     Failure/Error: get :show, params: {slug: occupation.to_param}
     
     ActionView::Template::Error:
       wrong number of arguments (given 2, expected 1)
     # /XXX/XXX/.rvm/gems/ruby-2.6.3/gems/react-rails-2.6.0/lib/react/rails/controller_lifecycle.rb:31:in `use_react_component_helper'
     # ./spec/controllers/occupations_controller_spec.rb:11:in `block (3 levels) in <top (required)>'

```

My action `show` is just a `show.html.erb` (without React)

### System configuration
**Sprockets or Webpacker version**: 4.2.0
**React-Rails version**: 2.6.0
**Rect_UJS version**: 2.6.0
**Rails version**: 6.0.1
**Ruby version**: 2.6.3

**Comment by BorisBresciani** [comment]
Error from RSpec: https://github.com/rspec/rspec-rails/issues/2177
