### ISSUE TITLE
Add support for ViteJs

### ISSUE THREAD

**Issue by ksweetie** [reactjs/react-rails#1134]
This is a feature suggestion, and I imagine it would be a ton of work, so I mainly just wanted to start a thread for discussion.

React-Rails already supports both Sprockets and Webpack. Adding support for [Vite](https://vitejs.dev/) would be great. There's a relatively new [vite_ruby](https://github.com/ElMassimo/vite_ruby) gem, and the author there commented on the feasibility of [using it with react-rails](https://github.com/ElMassimo/vite_ruby/discussions/86). In my case, the app I wanted to try it with uses SSR, so I didn't get very far in testing it out.

Any thoughts?

**Comment by BookOfGreg** [comment]
I'd be interested in seeing the popularity of vite or other packaging tools as I've not used it before.
I'd also be interested in making sure one maintainer uses vite primarily so that the points brought up by @ElMassimo are kept in mind when working on it. The point about using glob for context is something that I'm personally unaware of purely due to unfamiliarity for instance.

So this is a +1 if it's popular or upcoming and we have someone who is qualified to maintain this gem that would use vite regularly.

**Comment by pustomytnyk** [comment]
It is said that "Vite pre-bundles all of a project’s dependencies together into a single native JavaScript module with `esbuild`". And it is possible to import components for `esbuild` using plugin similar to https://github.com/rails/jsbundling-rails/compare/main...xiaohui-zhangxh:main (note how Stimulus controllers are imported by @xiaohui-zhangxh)

I tried this plugin (`/components` path and `.jsx` hardcoded)
```js
const componentPath = (module) => module.replace('./components/', '').replace('.jsx', '')
const glob  = require('glob').sync
// thanks: https://github.com/thomaschaaf/esbuild-plugin-import-glob
// thanks: https://github.com/rails/jsbundling-rails/compare/main...xiaohui-zhangxh:main
const ImportGlobPlugin = () => ({
  name: 'require-context',
  setup: (build) => {
    build.onResolve({ filter: /\*/ }, async (args) => {
      if (args.resolveDir === '') {
        return; // Ignore unresolvable paths
      }
      return {
        path: args.path,
        namespace: 'import-glob',
        pluginData: {
          resolveDir: args.resolveDir,
        },
      };
    });

    build.onLoad({ filter: /.*/, namespace: 'import-glob' }, async (args) => {
      const files = (
        glob(args.path, {
          cwd: args.pluginData.resolveDir,
        })
      ).sort();

      let importerCode = `
        ${files
        .map((module, index) => {
          return `import * as module${index} from '${module}'`})
        .join(';')}
        export default [${files
        .map((module, index) => `module${index}.default`)
        .join(',')}];
        export const context = {
          ${files.map((module, index) => `'${componentPath(module)}': module${index}.default`).join(',')}
        }
      `;

      return { contents: importerCode, resolveDir: args.pluginData.resolveDir };
    });
  },
});
```

Then in entrypoint this makes my components globally visible to react-rails
```js
import { context } from './components/**/*.jsx';
Object.keys(context).forEach((key) => {
  window[key] = context[key]
})
```

**Comment by Alxzu** [comment]
@pacMakaveli where that should be located? entrypoint? Thanks

**Comment by pacMakaveli** [comment]
> @pacMakaveli where that should be located? entrypoint? Thanks

I've put it in my main `application.js`. `app/packs/entrypoints/application.js`

**Comment by Alxzu** [comment]
Did anyone manage to implement vite + SSR successfully?

**Comment by ElMassimo** [comment]
@Alxzu Yes, see [this example with Inertia.js and React](https://github.com/ElMassimo/inertia-rails-ssr-template).

**Comment by Amit89480** [comment]
Can i help in fixing this issue?

**Comment by memoxmrdl** [comment]
Hi! 

I found a possible solution, on this line number https://github.com/reactjs/react-rails/blob/master/react_ujs/index.js#L79 I saw that and understood how it was made the constructor so, I take the code and it change a little bit and I do the following approach:

```
// app/javascript/helpers/viteConstructorRequireContext.js

export const viteConstructorRequireContext = function(reqCtx) {
  const fromRequireContext = function(reqCtx) {
    return function(className) {
      var parts = className.split(".");
      var filename = parts.shift();
      var keys = parts;
      // Load the module:
      var componentPath = Object.keys(reqCtx).find((path => path.search(filename) > 0));
      var component = reqCtx[componentPath];
      // Then access each key:
      keys.forEach(function(k) {
        component = component[k];
      });
      component = component.default;
      return component;
    }
  }

  const fromCtx = fromRequireContext(reqCtx);
  return function(className) {
    var component;
    try {
      // `require` will raise an error if this className isn't found:
      component = fromCtx(className);
    } catch (firstErr) {
      console.error(firstErr);
    }
    return component;
  }
}
```

```
// app/javascript/entrypoints/application.jsx

import ReactRailsUJS from "react_ujs";
import { viteConstructorRequireContext } from "../helpers/viteGetConstructor";

const componentsRequireContext = import.meta.globEager("~/components/main/**/*.{js,jsx}");
ReactRailsUJS.getConstructor = viteConstructorRequireContext(componentsRequireContext);
```

I expect that this approach it works for you.

**Comment by TrueDoleron** [comment]
@memoxmrdl Sorry, but in my try, dosen't work.
What's wrong in my example? 
<img width="1488" alt="Снимок экрана 2023-02-28 в 23 46 51" src="https://user-images.githubusercontent.com/17336921/221962705-28926c2a-da48-44f3-8a4a-53c127c610d7.png">

**Comment by paul-mesnilgrente** [comment]
@memoxmrdl That's awesome! I got the non-SSR pages working.

Is it going to work with SSR? I tried but nothing was displayed with no errors.

**Comment by paul-mesnilgrente** [comment]
Actually I found the exception:

```
=> #<React::ServerRendering::PrerenderError: Encountered error "#<ExecJS::ProgramError: TypeError: Cannot read properties of undefined (reading 'serverRender')>" when prerendering HelloWorld with {"name":"World"}
eval (eval at <anonymous> ((execjs):36:8), <anonymous>:6:45)
eval (eval at <anonymous> ((execjs):36:8), <anonymous>:18:13)
(execjs):36:8
(execjs):54:14
(execjs):1:40
Object.<anonymous> ((execjs):1:58)
Module._compile (node:internal/modules/cjs/loader:1103:14)
Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
Module.load (node:internal/modules/cjs/loader:981:32)
Function.Module._load (node:internal/modules/cjs/loader:822:12)
/home/paul/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/execjs-2.8.1/lib/execjs/external_runtime.rb:39:in `exec'
/home/paul/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/execjs-2.8.1/lib/execjs/external_runtime.rb:21:in `eval'
/home/paul/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/bundler/gems/react-rails-7814b829e645/lib/react/server_rendering/exec_js_renderer.rb:39:in `render_from_parts'
/home/paul/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/bundler/gems/react-rails-7814b829e645/lib/react/server_rendering/exec_js_renderer.rb:20:in `render'
/home/paul/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/bundler/gems/react-rails-7814b829e645/lib/react/server_rendering/bundle_renderer.rb:40:in `render'
/home/paul/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/bundler/gems/react-rails-7814b829e645/lib/react/server_rendering.rb:27:in `block in render'
/home/paul/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/connection_pool-2.4.1/lib/connection_pool.rb:110:in `block (2 levels) in with'
/home/paul/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/connection_pool-2.4.1/lib/connection_pool.rb:109:in `handle_interrupt'
/home/paul/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/connection_pool-2.4.1/lib/connection_pool.rb:109:in `block in with'
/home/paul/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/connection_pool-2.4.1/lib/connection_pool[2] pry(#<React::Rails::ComponentMount>)>
```

**Comment by ajesler-hatch** [comment]
> Hi!
> 
> I found a possible solution (for [Vite Ruby](https://vite-ruby.netlify.app/guide/rails.html)) on this line number https://github.com/reactjs/react-rails/blob/master/react_ujs/index.js#L79 I saw that and understood how it was made the constructor so, I take the code and it change a little bit and I do the following approach:

Thanks for posting this [memoxmrdl](https://github.com/memoxmrdl), it was super helpful. 
I found that if you have overlapping component names, then there is a chance it will return the wrong component. Eg searching for `NewForm` when you have components named `NewForm` and `SpecialNewForm`, you might get `SpecialNewForm`.

Our components tend to be named `directory/Name.js[x]` or `directory/Name/index.js[x]` so I've tweaked the code a little. This isn't 100% perfect, but works for our use case and naming style.
We don't use `A.B` to reference components, so I've removed the className splitting code.

Note that this won't work on windows as it assumes `/` for the path separator.

```javascript
// Based on https://github.com/reactjs/react-rails/issues/1134#issuecomment-1415112288
export const viteConstructorRequireContext = function(reqCtx) {
  const componentNameMatcher = className => {
    return path => {
      return (
        path.includes(`/${className}.js`) || path.includes(`/${className}/index.js`)
      );
    };
  };

  const fromRequireContext = function(reqCtx) {
    return function(className) {
      const componentPath = Object.keys(reqCtx).find(componentNameMatcher(className));

      const component = reqCtx[componentPath];
      return component.default;
    }
  }

  const fromCtx = fromRequireContext(reqCtx);
  return function(className) {
    var component;
    try {
      // `require` will raise an error if this className isn't found:
      component = fromCtx(className);
    } catch (firstErr) {
      console.error(firstErr);
    }
    return component;
  }
}
```

**Comment by justin808** [comment]
FWIW, I'm considering supporting Vite with https://github.com/shakacode/react_on_rails, including SSR. If anybody is interested in that, reply here, and consider our [Slack Channel](https://join.slack.com/t/reactrails/shared_invite/enQtNjY3NTczMjczNzYxLTlmYjdiZmY3MTVlMzU2YWE0OWM0MzNiZDI0MzdkZGFiZTFkYTFkOGVjODBmOWEyYWQ3MzA2NGE1YWJjNmVlMGE).

I suspect that Vite might work very easily with https://www.shakacode.com/react-on-rails-pro/, which is an easy migration from react-rails.

**Comment by jarommadsen** [comment]
The `viteConstructorRequireContext` method above did work except... it was importing every single React component in the `components` directory.

Ultimately, the real limitation of `react-rails` is that `mountComponents` works synchronously. If there were a `mountComponentsAsync` method, that would allow for identical support for Vite.

For now, I created this workaround:

```jsx
// app/javascript/helpers/createAsyncWrapper.jsx
import React, { useState, useEffect } from 'react';

function createAsyncWrapper(className, lazyComponents) {
  const path = Object.keys(lazyComponents).find((componentPath) => componentPath.endsWith(`/${className}.jsx`));

  if (!path) {
    // eslint-disable-next-line no-console
    console.error(`Could not find component: ${className}`);
    return () => (
      <div style={{ color: 'red' }}>
        Component not found:
        {className}
      </div>
    );
  }

  return function AsyncComponentWrapper(props) {
    const [Component, setComponent] = useState(null);

    useEffect(() => {
      let isMounted = true;
      lazyComponents[path]().then((mod) => {
        if (isMounted) setComponent(() => mod.default);
      });
      return () => {
        isMounted = false;
      };
    }, []);

    return Component ? <Component {...props} /> : null;
  };
}

export default createAsyncWrapper;
```

And then in `application.js`

```js
const componentsContext = import.meta.glob('../components/**/*.{js,jsx,ts,tsx}');
ReactRailsUJS.getConstructor = (name) => {
  return createAsyncWrapper(name, componentsContext);
};
```

This gives `react-rails` a single component to construct for each found component in the DOM and then the `useEffect` hook will lazy load the actual component and render it.

The downside is that this requires an initial React render cycle for the actual component to render... but good enough for my use case.

**Comment by satoharuto961-dev** [comment]
Thanks for starting this discussion! I agree that adding Vite support to React-Rails would be a really interesting improvement. Vite’s fast dev server and modern build pipeline could make React-Rails apps feel snappier and more modern compared to Webpack.

I’ve looked a bit at the vite_ruby gem—it does seem promising, and it’s encouraging that the author thinks integration is feasible. The tricky part, as you mentioned, will probably be SSR (server-side rendering) compatibility. React-Rails relies on a certain way of handling SSR assets and execution, and Vite’s setup might require some extra bridging code.

Even if full SSR support is challenging at first, I think experimenting with client-side React apps in a Rails + Vite setup could provide valuable insights. It could be a good first step before tackling SSR.

Overall, I’m very curious to see if someone in the community tries this out—it might open the door for more modern tooling in Rails React apps.
