### ISSUE TITLE
Read-only file system @ dir_s_mkdir - /components (Errno::EROFS) 

### ISSUE THREAD

**Issue by akhilgkrishnan** [reactjs/react-rails#1226]
Help us help you! Have you looked for similar issues? Do you have reproduction steps? [Contributing Guide](CONTRIBUTING.md#reporting-bugs)

### Steps to reproduce

(Guidelines for creating a bug report are [available
here](../CONTRIBUTING.md#reporting-bugs))

### Expected behavior
Tell us what should happen

### Actual behavior
I couldn't able to install the react-rails, while running `rails generate react:install`, on my local machine, I'm getting an error (which is mentioned below).

### System configuration
- **Shakapacker**: 6.5
- **React-Rails version**: 2.6
- **Rect_UJS version**:
- **Rails version**: 7.0.1
- **Ruby version**: 3.0.1

-------

```
/Users/akhilgkrishnan/.rvm/rubies/ruby-3.0.1/lib/ruby/3.0.0/fileutils.rb:253:in `mkdir': Read-only file system @ dir_s_mkdir - /components (Errno::EROFS)
	from /Users/akhilgkrishnan/.rvm/rubies/ruby-3.0.1/lib/ruby/3.0.0/fileutils.rb:253:in `fu_mkdir'
	from /Users/akhilgkrishnan/.rvm/rubies/ruby-3.0.1/lib/ruby/3.0.0/fileutils.rb:231:in `block (2 levels) in mkdir_p'
	from /Users/akhilgkrishnan/.rvm/rubies/ruby-3.0.1/lib/ruby/3.0.0/fileutils.rb:229:in `reverse_each'
	from /Users/akhilgkrishnan/.rvm/rubies/ruby-3.0.1/lib/ruby/3.0.0/fileutils.rb:229:in `block in mkdir_p'
	from /Users/akhilgkrishnan/.rvm/rubies/ruby-3.0.1/lib/ruby/3.0.0/fileutils.rb:211:in `each'
	from /Users/akhilgkrishnan/.rvm/rubies/ruby-3.0.1/lib/ruby/3.0.0/fileutils.rb:211:in `mkdir_p'
	from /Users/akhilgkrishnan/.rvm/gems/ruby-3.0.1/gems/thor-1.2.1/lib/thor/actions/empty_directory.rb:52:in `block in invoke!'
	from /Users/akhilgkrishnan/.rvm/gems/ruby-3.0.1/gems/thor-1.2.1/lib/thor/actions/empty_directory.rb:117:in `invoke_with_conflict_check'
	from /Users/akhilgkrishnan/.rvm/gems/ruby-3.0.1/gems/thor-1.2.1/lib/thor/actions/empty_directory.rb:50:in `invoke!'
	from /Users/akhilgkrishnan/.rvm/gems/ruby-3.0.1/gems/thor-1.2.1/lib/thor/actions.rb:93:in `action'
	from /Users/akhilgkrishnan/.rvm/gems/ruby-3.0.1/gems/thor-1.2.1/lib/thor/actions/empty_directory.rb:14:in `empty_directory'
	from /Users/akhilgkrishnan/.rvm/gems/ruby-3.0.1/gems/react-rails-2.6.0/lib/generators/react/install_generator.rb:26:in `create_directory'
	from /Users/akhilgkrishnan/.rvm/gems/ruby-3.0.1/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /Users/akhilgkrishnan/.rvm/gems/ruby-3.0.1/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/akhilgkrishnan/.rvm/gems/ruby-3.0.1/gems/thor-1.2.1/lib/thor/invocation.rb:134:in `block in invoke_all'
	from /Users/akhilgkrishnan/.rvm/gems/ruby-3.0.1/gems/thor-1.2.1/lib/thor/invocation.rb:134:in `each'
	from /Users/akhilgkrishnan/.rvm/gems/ruby-3.0.1/gems/thor-1.2.1/lib/thor/invocation.rb:134:in `map'
	from /Users/akhilgkrishnan/.rvm/gems/ruby-3.0.1/gems/thor-1.2.1/lib/thor/invocation.rb:134:in `invoke_all'
	from /Users/akhilgkrishnan/.rvm/gems/ruby-3.0.1/gems/thor-1.2.1/lib/thor/group.rb:232:in `dispatch'
	from /Users/akhilgkrishnan/.rvm/gems/ruby-3.0.1/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
	from /Users/akhilgkrishnan/.rvm/gems/ruby-3.0.1/gems/railties-7.0.4/lib/rails/generators.rb:263:in `invoke'
	from /Users/akhilgkrishnan/.rvm/gems/ruby-3.0.1/gems/railties-7.0.4/lib/rails/commands/generate/generate_command.rb:26:in `perform'
	from /Users/akhilgkrishnan/.rvm/gems/ruby-3.0.1/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /Users/akhilgkrishnan/.rvm/gems/ruby-3.0.1/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/akhilgkrishnan/.rvm/gems/ruby-3.0.1/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /Users/akhilgkrishnan/.rvm/gems/ruby-3.0.1/gems/railties-7.0.4/lib/rails/command/base.rb:87:in `perform'
	from /Users/akhilgkrishnan/.rvm/gems/ruby-3.0.1/gems/railties-7.0.4/lib/rails/command.rb:48:in `invoke'
	from /Users/akhilgkrishnan/.rvm/gems/ruby-3.0.1/gems/railties-7.0.4/lib/rails/commands.rb:18:in `<main>'
	from /Users/akhilgkrishnan/.rvm/gems/ruby-3.0.1/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /Users/akhilgkrishnan/.rvm/gems/ruby-3.0.1/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
```

**Comment by leovidal73** [comment]
I just got the exact same thing with ruby 2.7.5, rails 5.2.

**Comment by akhilgkrishnan** [comment]
> I just got the exact same thing with ruby 2.7.5, rails 5.2.

@leovidal73 Did you resolved that?

**Comment by ahangarha** [comment]
Thanks for reporting. This issue is already resolved and the fix will be available in the next release. Meanwhile please manually edit `config/webpacker.yml` and set `source_entry_path` to `packs`.

Please share the result.

**Comment by leovidal73** [comment]
It worked for me thank you !

**Comment by cworsley4** [comment]
Worked for me as well.
