### ISSUE TITLE
Guard rspec fails

### ISSUE THREAD

**Issue by nottombrown** [reactjs/react-rails#272]
```
14:01:52 - INFO - Running: spec/concerns/panel_with_links_spec.rb
/Users/tombrown/.rbenv/versions/2.1.5/lib/ruby/2.1.0/rubygems/dependency.rb:298:in `to_specs': Could not find 'bundler' (>= 0) among 149 total gem(s) (Gem::LoadError)
	from /Users/tombrown/.rbenv/versions/2.1.5/lib/ruby/2.1.0/rubygems/dependency.rb:309:in `to_spec'
	from /Users/tombrown/.rbenv/versions/2.1.5/lib/ruby/2.1.0/rubygems/core_ext/kernel_gem.rb:53:in `gem'
	from /Users/tombrown/.rbenv/versions/2.1.5/bin/bundle:22:in `<main>'
```

**Comment by rmosolgo** [comment]
Hey @nottombrown , I'm not sure how this is related to `react-rails`, can you clarify this issue a bit?

**Comment by nottombrown** [comment]
Whoops, totally posted in the wrong repo
