### ISSUE TITLE
ExecJS::ProgramError ReferenceError: Can't find variable: JSXTransformer

### ISSUE THREAD

**Issue by reneweteling** [reactjs/react-rails#294]
Hey There,

Just trying to create a new transformer, only when i use the master branch i get this error. When i switch back to the GEM all is well. Any idea's?

Thanks!

**Comment by rmosolgo** [comment]
Humm, I'm not sure. I just updated to master branch and it worked ok for me. Here's my Gemfile.lock entry:

```
GIT
  remote: git://github.com/reactjs/react-rails.git
  revision: 6019be97899c74ba351d7cf69877060c52e501d9
  specs:
    react-rails (1.0.0)
      coffee-script-source (~> 1.8)
      connection_pool
      execjs
      rails (>= 3.2)
      tilt
```

Could you please share some more information? For example:

- Your gemfile.lock entry for react-rails 
- The full stack trace of the exception 

It's hard to debug without specifics!

**Comment by reneweteling** [comment]
Hey @rmosolgo,

Sorry for the delay, didnt get around to it. Also sorry for not providing the correct information to start with, im trying to educate my own testers and now im doing the same with you. Mea Culpa!

Lockfile
````
GIT
  remote: git://github.com/reactjs/react-rails.git
  revision: 6019be97899c74ba351d7cf69877060c52e501d9
  specs:
    react-rails (1.0.0)
      coffee-script-source (~> 1.8)
      connection_pool
      execjs
      rails (>= 3.2)
      tilt
````

Stack for: "ReferenceError: Can't find variable: JSXTransformer"
````
(execjs):2:12
(execjs):6:21
(execjs):1:46
global code@(execjs):1:58
vendor/ruby/2.2.0/gems/execjs-2.5.2/lib/execjs/external_runtime.rb:39:in `exec'
vendor/ruby/2.2.0/gems/execjs-2.5.2/lib/execjs/external_runtime.rb:21:in `eval'
vendor/ruby/2.2.0/gems/execjs-2.5.2/lib/execjs/external_runtime.rb:46:in `call'
vendor/ruby/2.2.0/bundler/gems/react-rails-6019be97899c/lib/react/jsx/transformer.rb:22:in `transform'
vendor/ruby/2.2.0/bundler/gems/react-rails-6019be97899c/lib/react/jsx.rb:17:in `transform'
vendor/ruby/2.2.0/bundler/gems/react-rails-6019be97899c/lib/react/jsx/template.rb:13:in `evaluate'
vendor/ruby/2.2.0/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
vendor/ruby/2.2.0/gems/sprockets-2.12.3/lib/sprockets/context.rb:197:in `block in evaluate'
vendor/ruby/2.2.0/gems/sprockets-2.12.3/lib/sprockets/context.rb:194:in `each'
vendor/ruby/2.2.0/gems/sprockets-2.12.3/lib/sprockets/context.rb:194:in `evaluate'
vendor/ruby/2.2.0/gems/sprockets-2.12.3/lib/sprockets/processed_asset.rb:12:in `initialize'
vendor/ruby/2.2.0/gems/sprockets-2.12.3/lib/sprockets/base.rb:374:in `new'
vendor/ruby/2.2.0/gems/sprockets-2.12.3/lib/sprockets/base.rb:374:in `block in build_asset'
vendor/ruby/2.2.0/gems/sprockets-2.12.3/lib/sprockets/base.rb:395:in `circular_call_protection'
vendor/ruby/2.2.0/gems/sprockets-2.12.3/lib/sprockets/base.rb:373:in `build_asset'
vendor/ruby/2.2.0/gems/sprockets-2.12.3/lib/sprockets/index.rb:94:in `block in build_asset'
vendor/ruby/2.2.0/gems/sprockets-2.12.3/lib/sprockets/caching.rb:58:in `cache_asset'
vendor/ruby/2.2.0/gems/sprockets-2.12.3/lib/sprockets/index.rb:93:in `build_asset'
vendor/ruby/2.2.0/gems/sprockets-2.12.3/lib/sprockets/base.rb:287:in `find_asset'
vendor/ruby/2.2.0/gems/sprockets-2.12.3/lib/sprockets/index.rb:61:in `find_asset'
vendor/ruby/2.2.0/gems/sprockets-2.12.3/lib/sprockets/processed_asset.rb:111:in `block in resolve_dependencies'
vendor/ruby/2.2.0/gems/sprockets-2.12.3/lib/sprockets/processed_asset.rb:105:in `each'
vendor/ruby/2.2.0/gems/sprockets-2.12.3/lib/sprockets/processed_asset.rb:105:in `resolve_dependencies'
vendor/ruby/2.2.0/gems/sprockets-2.12.3/lib/sprockets/processed_asset.rb:97:in `build_required_assets'
vendor/ruby/2.2.0/gems/sprockets-2.12.3/lib/sprockets/processed_asset.rb:16:in `initialize'
vendor/ruby/2.2.0/gems/sprockets-2.12.3/lib/sprockets/base.rb:374:in `new'
vendor/ruby/2.2.0/gems/sprockets-2.12.3/lib/sprockets/base.rb:374:in `block in build_asset'
vendor/ruby/2.2.0/gems/sprockets-2.12.3/lib/sprockets/base.rb:395:in `circular_call_protection'
vendor/ruby/2.2.0/gems/sprockets-2.12.3/lib/sprockets/base.rb:373:in `build_asset'
vendor/ruby/2.2.0/gems/sprockets-2.12.3/lib/sprockets/index.rb:94:in `block in build_asset'
vendor/ruby/2.2.0/gems/sprockets-2.12.3/lib/sprockets/caching.rb:58:in `cache_asset'
vendor/ruby/2.2.0/gems/sprockets-2.12.3/lib/sprockets/index.rb:93:in `build_asset'
vendor/ruby/2.2.0/gems/sprockets-2.12.3/lib/sprockets/base.rb:287:in `find_asset'
vendor/ruby/2.2.0/gems/sprockets-2.12.3/lib/sprockets/index.rb:61:in `find_asset'
vendor/ruby/2.2.0/gems/sprockets-2.12.3/lib/sprockets/bundled_asset.rb:16:in `initialize'
vendor/ruby/2.2.0/gems/sprockets-2.12.3/lib/sprockets/base.rb:377:in `new'
vendor/ruby/2.2.0/gems/sprockets-2.12.3/lib/sprockets/base.rb:377:in `build_asset'
vendor/ruby/2.2.0/gems/sprockets-2.12.3/lib/sprockets/index.rb:94:in `block in build_asset'
vendor/ruby/2.2.0/gems/sprockets-2.12.3/lib/sprockets/caching.rb:58:in `cache_asset'
vendor/ruby/2.2.0/gems/sprockets-2.12.3/lib/sprockets/index.rb:93:in `build_asset'
vendor/ruby/2.2.0/gems/sprockets-2.12.3/lib/sprockets/base.rb:287:in `find_asset'
vendor/ruby/2.2.0/gems/sprockets-2.12.3/lib/sprockets/index.rb:61:in `find_asset'
vendor/ruby/2.2.0/gems/sprockets-2.12.3/lib/sprockets/environment.rb:75:in `find_asset'
vendor/ruby/2.2.0/gems/sprockets-2.12.3/lib/sprockets/base.rb:295:in `[]'
vendor/ruby/2.2.0/gems/sprockets-rails-2.3.1/lib/sprockets/rails/helper.rb:243:in `lookup_asset_for_path'
vendor/ruby/2.2.0/gems/sprockets-rails-2.3.1/lib/sprockets/rails/helper.rb:203:in `check_errors_for'
vendor/ruby/2.2.0/gems/sprockets-rails-2.3.1/lib/sprockets/rails/helper.rb:150:in `block in javascript_include_tag'
vendor/ruby/2.2.0/gems/sprockets-rails-2.3.1/lib/sprockets/rails/helper.rb:149:in `map'
vendor/ruby/2.2.0/gems/sprockets-rails-2.3.1/lib/sprockets/rails/helper.rb:149:in `javascript_include_tag'
app/views/layouts/application.html.slim:4:in `_app_views_layouts_application_html_slim___3397513199341851106_70313750162340'
vendor/ruby/2.2.0/gems/actionview-4.2.1/lib/action_view/template.rb:145:in `block in render'
vendor/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/notifications.rb:166:in `instrument'
vendor/ruby/2.2.0/gems/actionview-4.2.1/lib/action_view/template.rb:333:in `instrument'
vendor/ruby/2.2.0/gems/actionview-4.2.1/lib/action_view/template.rb:143:in `render'
vendor/ruby/2.2.0/gems/actionview-4.2.1/lib/action_view/renderer/template_renderer.rb:66:in `render_with_layout'
vendor/ruby/2.2.0/gems/actionview-4.2.1/lib/action_view/renderer/template_renderer.rb:52:in `render_template'
vendor/ruby/2.2.0/gems/actionview-4.2.1/lib/action_view/renderer/template_renderer.rb:14:in `render'
vendor/ruby/2.2.0/gems/actionview-4.2.1/lib/action_view/renderer/renderer.rb:42:in `render_template'
vendor/ruby/2.2.0/gems/actionview-4.2.1/lib/action_view/renderer/renderer.rb:23:in `render'
vendor/ruby/2.2.0/gems/actionview-4.2.1/lib/action_view/rendering.rb:100:in `_render_template'
vendor/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal/streaming.rb:217:in `_render_template'
vendor/ruby/2.2.0/gems/actionview-4.2.1/lib/action_view/rendering.rb:83:in `render_to_body'
vendor/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal/rendering.rb:32:in `render_to_body'
vendor/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal/renderers.rb:37:in `render_to_body'
vendor/ruby/2.2.0/gems/actionpack-4.2.1/lib/abstract_controller/rendering.rb:25:in `render'
vendor/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal/rendering.rb:16:in `render'
vendor/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
vendor/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
/Users/rene/.rbenv/versions/2.2.1/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
vendor/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/core_ext/benchmark.rb:12:in `ms'
vendor/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal/instrumentation.rb:44:in `block in render'
vendor/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
vendor/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
vendor/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal/instrumentation.rb:43:in `render'
vendor/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal/implicit_render.rb:10:in `default_render'
vendor/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal/implicit_render.rb:5:in `send_action'
vendor/ruby/2.2.0/gems/actionpack-4.2.1/lib/abstract_controller/base.rb:198:in `process_action'
vendor/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal/rendering.rb:10:in `process_action'
vendor/ruby/2.2.0/gems/actionpack-4.2.1/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
vendor/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:117:in `call'
vendor/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:117:in `call'
vendor/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
vendor/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:505:in `call'
vendor/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:505:in `call'
vendor/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:92:in `_run_callbacks'
vendor/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:776:in `_run_process_action_callbacks'
vendor/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
vendor/ruby/2.2.0/gems/actionpack-4.2.1/lib/abstract_controller/callbacks.rb:19:in `process_action'
vendor/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal/rescue.rb:29:in `process_action'
vendor/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
vendor/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/notifications.rb:164:in `block in instrument'
vendor/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
vendor/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/notifications.rb:164:in `instrument'
vendor/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
vendor/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
vendor/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
vendor/ruby/2.2.0/gems/actionpack-4.2.1/lib/abstract_controller/base.rb:137:in `process'
vendor/ruby/2.2.0/gems/actionview-4.2.1/lib/action_view/rendering.rb:30:in `process'
vendor/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal.rb:196:in `dispatch'
vendor/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
vendor/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal.rb:237:in `block in action'
vendor/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/routing/route_set.rb:74:in `call'
vendor/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
vendor/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/routing/route_set.rb:43:in `serve'
vendor/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/journey/router.rb:43:in `block in serve'
vendor/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/journey/router.rb:30:in `each'
vendor/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/journey/router.rb:30:in `serve'
vendor/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/routing/route_set.rb:819:in `call'
vendor/ruby/2.2.0/gems/rack-1.6.1/lib/rack/etag.rb:24:in `call'
vendor/ruby/2.2.0/gems/rack-1.6.1/lib/rack/conditionalget.rb:25:in `call'
vendor/ruby/2.2.0/gems/rack-1.6.1/lib/rack/head.rb:13:in `call'
vendor/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
vendor/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/flash.rb:260:in `call'
vendor/ruby/2.2.0/gems/rack-1.6.1/lib/rack/session/abstract/id.rb:225:in `context'
vendor/ruby/2.2.0/gems/rack-1.6.1/lib/rack/session/abstract/id.rb:220:in `call'
vendor/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/cookies.rb:560:in `call'
vendor/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/query_cache.rb:36:in `call'
vendor/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:649:in `call'
vendor/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:378:in `call'
vendor/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
vendor/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:88:in `call'
vendor/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:88:in `_run_callbacks'
vendor/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:776:in `_run_call_callbacks'
vendor/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
vendor/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
vendor/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/reloader.rb:73:in `call'
vendor/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
vendor/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
vendor/ruby/2.2.0/gems/web-console-2.1.2/lib/web_console/middleware.rb:37:in `call'
vendor/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
vendor/ruby/2.2.0/gems/railties-4.2.1/lib/rails/rack/logger.rb:38:in `call_app'
vendor/ruby/2.2.0/gems/railties-4.2.1/lib/rails/rack/logger.rb:20:in `block in call'
vendor/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/tagged_logging.rb:68:in `block in tagged'
vendor/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/tagged_logging.rb:26:in `tagged'
vendor/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/tagged_logging.rb:68:in `tagged'
vendor/ruby/2.2.0/gems/railties-4.2.1/lib/rails/rack/logger.rb:20:in `call'
vendor/ruby/2.2.0/gems/quiet_assets-1.1.0/lib/quiet_assets.rb:27:in `call_with_quiet_assets'
vendor/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/request_id.rb:21:in `call'
vendor/ruby/2.2.0/gems/rack-1.6.1/lib/rack/methodoverride.rb:22:in `call'
vendor/ruby/2.2.0/gems/rack-1.6.1/lib/rack/runtime.rb:18:in `call'
vendor/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
vendor/ruby/2.2.0/gems/rack-1.6.1/lib/rack/lock.rb:17:in `call'
vendor/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/static.rb:113:in `call'
vendor/ruby/2.2.0/gems/rack-1.6.1/lib/rack/sendfile.rb:113:in `call'
vendor/ruby/2.2.0/gems/railties-4.2.1/lib/rails/engine.rb:518:in `call'
vendor/ruby/2.2.0/gems/railties-4.2.1/lib/rails/application.rb:164:in `call'
vendor/ruby/2.2.0/gems/rack-1.6.1/lib/rack/lock.rb:17:in `call'
vendor/ruby/2.2.0/gems/rack-1.6.1/lib/rack/content_length.rb:15:in `call'
vendor/ruby/2.2.0/gems/rack-1.6.1/lib/rack/handler/webrick.rb:89:in `service'
/Users/rene/.rbenv/versions/2.2.1/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
/Users/rene/.rbenv/versions/2.2.1/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
/Users/rene/.rbenv/versions/2.2.1/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'
````

Thanks!

**Comment by reneweteling** [comment]
If you are curious, ive checked the code in so you can see whats happening

https://github.com/reneweteling/react-slim/tree/issue-with-react-rails-git

Thanks!

**Comment by rmosolgo** [comment]
Thanks, that's very helpful! 

I cloned it and started it up. I also added the `better_errors` & `binding_of_caller` gems. 

I found that `JSXTransformer#jsx_transform_code` was returning _nothing_ instead of returning the JSXTransformer source. Then I saw that the Ruby transformer was looking for the JS code in a non-existent location:

![image](https://cloud.githubusercontent.com/assets/2231765/8149177/6e58358c-126f-11e5-9e3e-6d279a9c72a0.png)


I think this line is causing the problem:

https://github.com/reneweteling/react-slim/blob/ed5f379d4664cc717fcb9910a4491a7721f600be/config/environments/development.rb#L45

(Maybe it was copy-pasted from the readme?)

**Comment by reneweteling** [comment]
ok... now i feel stupid! Thanks for pointing out the obvious... should get more sleep haha! The slim parser is coming along, ill let you know when its done!
