### ISSUE TITLE
Can't install on Rails 4.2.4. Generator hangs and does nothing

### ISSUE THREAD

**Issue by iDev0urer** [reactjs/react-rails#381]
This seems to be different from the similar issue #331. I dropped `react-rails` into a brand new Rails app and when I try to run the generator it hangs. When I press `ctrl + c` to stop it I get this:

```
^C/Users/chris/.rvm/gems/ruby-2.2.2/gems/spring-1.4.0/lib/spring/client/run.rb:98:in `gets': Interrupt
        from /Users/chris/.rvm/gems/ruby-2.2.2/gems/spring-1.4.0/lib/spring/client/run.rb:98:in `verify_server_version'
        from /Users/chris/.rvm/gems/ruby-2.2.2/gems/spring-1.4.0/lib/spring/client/run.rb:56:in `run'
        from /Users/chris/.rvm/gems/ruby-2.2.2/gems/spring-1.4.0/lib/spring/client/run.rb:37:in `warm_run'
        from /Users/chris/.rvm/gems/ruby-2.2.2/gems/spring-1.4.0/lib/spring/client/run.rb:26:in `call'
        from /Users/chris/.rvm/gems/ruby-2.2.2/gems/spring-1.4.0/lib/spring/client/command.rb:7:in `call'
        from /Users/chris/.rvm/gems/ruby-2.2.2/gems/spring-1.4.0/lib/spring/client/rails.rb:24:in `call'
        from /Users/chris/.rvm/gems/ruby-2.2.2/gems/spring-1.4.0/lib/spring/client/command.rb:7:in `call'
        from /Users/chris/.rvm/gems/ruby-2.2.2/gems/spring-1.4.0/lib/spring/client.rb:28:in `run'
        from /Users/chris/.rvm/gems/ruby-2.2.2/gems/spring-1.4.0/bin/spring:49:in `<top (required)>'
        from /Users/chris/.rvm/gems/ruby-2.2.2/gems/spring-1.4.0/lib/spring/binstub.rb:11:in `load'
        from /Users/chris/.rvm/gems/ruby-2.2.2/gems/spring-1.4.0/lib/spring/binstub.rb:11:in `<top (required)>'
        from /Users/chris/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /Users/chris/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /Users/chris/Documents/Projects/Personal/blog.cwatsondev.com/bin/spring:13:in `<top (required)>'
        from bin/rails:3:in `load'
        from bin/rails:3:in `<main>'
```

My Gemfile.lock: 

```
GEM
  remote: https://rubygems.org/
  remote: https://rails-assets.org/
  specs:
    actionmailer (4.2.4)
      actionpack (= 4.2.4)
      actionview (= 4.2.4)
      activejob (= 4.2.4)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 1.0, >= 1.0.5)
    actionpack (4.2.4)
      actionview (= 4.2.4)
      activesupport (= 4.2.4)
      rack (~> 1.6)
      rack-test (~> 0.6.2)
      rails-dom-testing (~> 1.0, >= 1.0.5)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    actionview (4.2.4)
      activesupport (= 4.2.4)
      builder (~> 3.1)
      erubis (~> 2.7.0)
      rails-dom-testing (~> 1.0, >= 1.0.5)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    activejob (4.2.4)
      activesupport (= 4.2.4)
      globalid (>= 0.3.0)
    activemodel (4.2.4)
      activesupport (= 4.2.4)
      builder (~> 3.1)
    activerecord (4.2.4)
      activemodel (= 4.2.4)
      activesupport (= 4.2.4)
      arel (~> 6.0)
    activesupport (4.2.4)
      i18n (~> 0.7)
      json (~> 1.7, >= 1.7.7)
      minitest (~> 5.1)
      thread_safe (~> 0.3, >= 0.3.4)
      tzinfo (~> 1.1)
    arel (6.0.3)
    babel-source (5.8.26)
    babel-transpiler (0.7.0)
      babel-source (>= 4.0, < 6)
      execjs (~> 2.0)
    better_errors (2.1.1)
      coderay (>= 1.0.0)
      erubis (>= 2.6.6)
      rack (>= 0.9.0)
    binding_of_caller (0.7.2)
      debug_inspector (>= 0.0.1)
    builder (3.2.2)
    byebug (6.0.2)
    climate_control (0.0.3)
      activesupport (>= 3.0)
    cocaine (0.5.7)
      climate_control (>= 0.0.3, < 1.0)
    coderay (1.1.0)
    coffee-rails (4.1.0)
      coffee-script (>= 2.2.0)
      railties (>= 4.0.0, < 5.0)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.9.1.1)
    connection_pool (2.2.0)
    debug_inspector (0.0.2)
    dotenv (2.0.2)
    dotenv-rails (2.0.2)
      dotenv (= 2.0.2)
      railties (~> 4.0)
    erubis (2.7.0)
    execjs (2.6.0)
    globalid (0.3.6)
      activesupport (>= 4.1.0)
    i18n (0.7.0)
    jbuilder (2.3.2)
      activesupport (>= 3.0.0, < 5)
      multi_json (~> 1.2)
    jquery-rails (4.0.5)
      rails-dom-testing (~> 1.0)
      railties (>= 4.2.0)
      thor (>= 0.14, < 2.0)
    json (1.8.3)
    loofah (2.0.3)
      nokogiri (>= 1.5.9)
    mail (2.6.3)
      mime-types (>= 1.16, < 3)
    mime-types (2.6.2)
    mimemagic (0.3.0)
    mini_portile (0.6.2)
    minitest (5.8.1)
    multi_json (1.11.2)
    nokogiri (1.6.6.2)
      mini_portile (~> 0.6.0)
    paperclip (4.3.1)
      activemodel (>= 3.2.0)
      activesupport (>= 3.2.0)
      cocaine (~> 0.5.5)
      mime-types
      mimemagic (= 0.3.0)
    passenger (5.0.21)
      rack
      rake (>= 0.8.1)
    rack (1.6.4)
    rack-test (0.6.3)
      rack (>= 1.0)
    rails (4.2.4)
      actionmailer (= 4.2.4)
      actionpack (= 4.2.4)
      actionview (= 4.2.4)
      activejob (= 4.2.4)
      activemodel (= 4.2.4)
      activerecord (= 4.2.4)
      activesupport (= 4.2.4)
      bundler (>= 1.3.0, < 2.0)
      railties (= 4.2.4)
      sprockets-rails
    rails-assets-highlight (8.9.1)
    rails-deprecated_sanitizer (1.0.3)
      activesupport (>= 4.2.0.alpha)
    rails-dom-testing (1.0.7)
      activesupport (>= 4.2.0.beta, < 5.0)
      nokogiri (~> 1.6.0)
      rails-deprecated_sanitizer (>= 1.0.1)
    rails-html-sanitizer (1.0.2)
      loofah (~> 2.0)
    railties (4.2.4)
      actionpack (= 4.2.4)
      activesupport (= 4.2.4)
      rake (>= 0.8.7)
      thor (>= 0.18.1, < 2.0)
    rake (10.4.2)
    rdoc (4.2.0)
    react-rails (1.4.1)
      babel-transpiler (>= 0.7.0)
      coffee-script-source (~> 1.8)
      connection_pool
      execjs
      rails (>= 3.2)
      tilt
    rouge (1.10.1)
    sass (3.4.19)
    sass-rails (5.0.4)
      railties (>= 4.0.0, < 5.0)
      sass (~> 3.1)
      sprockets (>= 2.8, < 4.0)
      sprockets-rails (>= 2.0, < 4.0)
      tilt (>= 1.1, < 3)
    sdoc (0.4.1)
      json (~> 1.7, >= 1.7.7)
      rdoc (~> 4.0)
    spring (1.4.0)
    sprockets (3.4.0)
      rack (> 1, < 3)
    sprockets-rails (2.3.3)
      actionpack (>= 3.0)
      activesupport (>= 3.0)
      sprockets (>= 2.8, < 4.0)
    sqlite3 (1.3.11)
    thor (0.19.1)
    thread_safe (0.3.5)
    tilt (2.0.1)
    turbolinks (2.5.3)
      coffee-rails
    tzinfo (1.2.2)
      thread_safe (~> 0.1)
    uglifier (2.7.2)
      execjs (>= 0.3.0)
      json (>= 1.8.0)
    web-console (2.2.1)
      activemodel (>= 4.0)
      binding_of_caller (>= 0.7.2)
      railties (>= 4.0)
      sprockets-rails (>= 2.0, < 4.0)

PLATFORMS
  ruby

DEPENDENCIES
  better_errors
  byebug
  coffee-rails (~> 4.1.0)
  dotenv-rails
  jbuilder (~> 2.0)
  jquery-rails
  paperclip
  passenger
  rails (= 4.2.4)
  rails-assets-highlight!
  react-rails (~> 1.4.0)
  rouge
  sass-rails (~> 5.0)
  sdoc (~> 0.4.0)
  spring
  sqlite3
  turbolinks
  uglifier (>= 1.3.0)
  web-console (~> 2.0)

BUNDLED WITH
   1.10.6
```

**Comment by iDev0urer** [comment]
Never mind. It actually seems as though my generators are broken period.
