### ISSUE TITLE
Duplicate data property in object literal not allowed in strict mode while parsing

### ISSUE THREAD

**Issue by AnuragRamdasan** [reactjs/react-rails#420]
I am seeing this error on my react-rails rendering using react-components-client.

```
Error while running `/Users/anurag/Desktop/temp/savannah/./node_modules/.bin/browserify -d -t [ babelify --presets [ es2015 react ] ] --transform [ reactify --harmony ] --extension=".jsx" --list -`:

events.js:141
      throw er; // Unhandled 'error' event
      ^

ReactifyError: /Users/anurag/Desktop/temp/savannah/app/assets/javascripts/components/ActivityStream.jsx: Parse Error: Line 155: Duplicate data property in object literal not allowed in strict mode while parsing file: /Users/anurag/Desktop/temp/savannah/app/assets/javascripts/components/ActivityStream.jsx
    at throwError (/Users/anurag/Desktop/temp/savannah/node_modules/react-tools/node_modules/esprima-fb/esprima.js:2813:21)
    at throwErrorTolerant (/Users/anurag/Desktop/temp/savannah/node_modules/react-tools/node_modules/esprima-fb/esprima.js:2825:24)
    at parseObjectInitialiser (/Users/anurag/Desktop/temp/savannah/node_modules/react-tools/node_modules/esprima-fb/esprima.js:3399:29)
    at parsePrimaryExpression (/Users/anurag/Desktop/temp/savannah/node_modules/react-tools/node_modules/esprima-fb/esprima.js:3553:20)
    at parseLeftHandSideExpressionAllowCall (/Users/anurag/Desktop/temp/savannah/node_modules/react-tools/node_modules/esprima-fb/esprima.js:3656:61)
    at parsePostfixExpression (/Users/anurag/Desktop/temp/savannah/node_modules/react-tools/node_modules/esprima-fb/esprima.js:3696:20)
    at parseUnaryExpression (/Users/anurag/Desktop/temp/savannah/node_modules/react-tools/node_modules/esprima-fb/esprima.js:3763:16)
    at parseBinaryExpression (/Users/anurag/Desktop/temp/savannah/node_modules/react-tools/node_modules/esprima-fb/esprima.js:3853:16)
    at parseConditionalExpression (/Users/anurag/Desktop/temp/savannah/node_modules/react-tools/node_modules/esprima-fb/esprima.js:3913:16)
    at parseAssignmentExpression (/Users/anurag/Desktop/temp/savannah/node_modules/react-tools/node_modules/esprima-fb/esprima.js:4166:16)
```

This happens on the line `this.setState({error: true})` so its not directly a syntax issue. 
I am guessing somewhere the browserify is unable to transform the jsx file for some reason.

Using react-rails 1.5.0

**Comment by rmosolgo** [comment]
Can you share the source for the file in question (`ActivityStream.jsx`)?

**Comment by dmitrye** [comment]
I am having the same error and I think I found the issue. Looks like reactify doesnt like empty attributes. I have className="" in a <form> element that was causing the error across a dozen pages. As soon as I removed it the errors went away.
