### ISSUE TITLE
Capybara::Poltergeist::JavascriptErrors after adding React to Rails app.

### ISSUE THREAD

**Issue by msojka** [reactjs/react-rails#515]
Help us help you! Please choose one:

- [ ] I have another issue to discuss.

-------

Hello,

I'm having issues running tests after adding react to rails app.

First it was this:

```
Capybara::Poltergeist::JavascriptError

      One or more errors were raised in the Javascript code on the page. If you don't care about these errors, you can ignore them by setting js_errors: false in your Poltergeist configuration (see documentation for details).

TypeError: 'undefined' is not a function (evaluating 'RegExp.prototype.test.bind(new RegExp('^(data|aria)-[' + DOMProperty.ATTRIBUTE_NAME_CHAR + ']*$'))')
TypeError: 'undefined' is not a function (evaluating 'RegExp.prototype.test.bind(new RegExp('^(data|aria)-[' + DOMProperty.ATTRIBUTE_NAME_CHAR + ']*$'))')
    at http://127.0.0.1:37983/assets/application.js:35345
    ...
    at http://127.0.0.1:37983/assets/application.js:51426
ReferenceError: Can't find variable: I18n
ReferenceError: Can't find variable: I18n
    at http://127.0.0.1:37983/users/sign_in:60
./spec/support/login_support.rb:3:in `login_user'
```

After adding `Function.Prototype.bind` polyfill as suggested here https://github.com/facebook/react/pull/347#issuecomment-25981408 I'm down to this:

```
TypeError: instanceof called on an object with an invalid prototype property.
TypeError: instanceof called on an object with an invalid prototype property.
    at http://127.0.0.1:42548/assets/application.js:32095
    ...
    at http://127.0.0.1:42548/assets/application.js:74352
ReferenceError: Can't find variable: I18n
ReferenceError: Can't find variable: I18n
    at http://127.0.0.1:42548/users/sign_in:60
./spec/support/login_support.rb:3:in `login_user'
```

Any tips while I'm trying to dig deeper?

BTW. here's the login_user method from `./spec/support/login_support.rb`

```
def login_user(user)
    visit "/"

    fill_in "user_email", with: user.email
    fill_in "user_password", with: "password"

    click_button I18n.t("login.button")
  end
```

**Comment by rmosolgo** [comment]
Strange strange ...

I see this part of the polyfill: 

```js
    fNOP.prototype = this.prototype;
    fBound.prototype = new fNOP();
```

I wonder if that's causing 

```
TypeError: instanceof called on an object with an invalid prototype property.
```

But, I would have thought someone else on that ReactJS thread would have had the same problem....


What about 

```
ReferenceError: Can't find variable: I18n
```

? Is that error coming from JavaScript, or from Ruby? I mean, is there a missing value in JS somewhere?

**Comment by msojka** [comment]
This works: https://gist.github.com/noradaiko/56345a10b396cefa4dfd

Thanks.

**Comment by puregold117** [comment]
I'd love to see the gist but it says `Not found`. Could you plz ensure that link works?
