### ISSUE TITLE
prerender: true causes V8::Error - Unexpected token <

### ISSUE THREAD

**Issue by KurtRMueller** [reactjs/react-rails#55]
Hey guys,

Whenever I pass in the `prerender: true` option to the options hash of a react component, I get the error: `V8::Error - Unexpected token <`. My component works fine when i remove `prerender: true` from the options hash.

Gemfile:
```ruby
gem 'rails', '4.1.1'
gem 'execjs'
gem 'therubyracer', platforms: :ruby
gem 'react-rails', github: 'reactjs/react-rails'
```

The view:
```ruby
= react_component("AssignmentWindowProgressBar", { assignment: @assignment_json }, { prerender: true })
```

Coffee file:
```coffee
###* @jsx React.DOM ###

@AssignmentWindowProgressBar = React.createClass
  render: ->
    `<div>Hi world.</div>`

# this is located in this file:
# ./apps/assets/javascripts/components/assignments/AssignmentWindows.js.jsx.coffee
```

Stack trace:
```
V8::Error - Unexpected token < at <eval>:19037:15:
  therubyracer (0.12.1) lib/v8/error.rb:86:in `block in try'
  therubyracer (0.12.1) lib/v8/error.rb:83:in `try'
  therubyracer (0.12.1) lib/v8/context.rb:95:in `block in eval'
  therubyracer (0.12.1) lib/v8/context.rb:248:in `block (2 levels) in lock_scope_and_enter'
  therubyracer (0.12.1) lib/v8/context.rb:245:in `block in lock_scope_and_enter'
  therubyracer (0.12.1) lib/v8/context.rb:244:in `lock_scope_and_enter'
  therubyracer (0.12.1) lib/v8/context.rb:204:in `enter'
  therubyracer (0.12.1) lib/v8/context.rb:94:in `eval'
  execjs (2.2.0) lib/execjs/ruby_racer_runtime.rb:11:in `block in initialize'
  execjs (2.2.0) lib/execjs/ruby_racer_runtime.rb:78:in `block in lock'
  execjs (2.2.0) lib/execjs/ruby_racer_runtime.rb:76:in `lock'
  execjs (2.2.0) lib/execjs/ruby_racer_runtime.rb:9:in `initialize'
  execjs (2.2.0) lib/execjs/runtime.rb:44:in `compile'
  execjs (2.2.0) lib/execjs/module.rb:27:in `compile'
  ... end of execjs errors ...
```

Thanks for any and all help guys! Appreciate all the work and effort you all have put in to this great project.

**Comment by rmosolgo** [comment]
I hope this issue was worked out! Server rendering is very different now, please open another issue if you're having a problem with it!
