### ISSUE TITLE
Encoding::UndefinedConversionError when prerendering component

### ISSUE THREAD

**Issue by matthieua** [reactjs/react-rails#613]
- [x] My app crashes with `react-rails`, so I've included the stack trace and the exact steps which make it crash.
- [x] I'm trying to use `react-rails` with another library, but I'm having trouble. I've described my JavaScript management setup (eg, Sprockets, Webpack...), how I'm trying to use this other library, and why it's not working.

-------

When prerendering components, I'm getting `"\xE2" from ASCII-8BIT to UTF-8` `Encoding::UndefinedConversionError` and I have no idea where it's from. I'm using webpack to compile my assets but I don't think this is related. I've tried to remove depencies and been able to reproduce this error with different components.

Here is the stacktrace:
```
execjs (2.7.0) lib/execjs/encoding.rb:22:in `encode'
execjs (2.7.0) lib/execjs/encoding.rb:22:in `encode'
execjs (2.7.0) lib/execjs/ruby_racer_runtime.rb:7:in `initialize'
execjs (2.7.0) lib/execjs/runtime.rb:57:in `new'
execjs (2.7.0) lib/execjs/runtime.rb:57:in `compile'
execjs (2.7.0) lib/execjs/module.rb:27:in `compile'
react-rails (1.9.0) lib/react/server_rendering/exec_js_renderer.rb:10:in `initialize'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/webpack-rails-90b21c2dd51c/lib/webpack/rails/react_server_renderer.rb:18:in `initialize'
react-rails (1.9.0) lib/react/server_rendering.rb:22:in `new'
react-rails (1.9.0) lib/react/server_rendering.rb:22:in `create_renderer'
react-rails (1.9.0) lib/react/server_rendering.rb:12:in `block in reset_pool'
connection_pool (2.2.0) lib/connection_pool/timed_stack.rb:169:in `try_create'
connection_pool (2.2.0) lib/connection_pool/timed_stack.rb:81:in `block (2 levels) in pop'
connection_pool (2.2.0) lib/connection_pool/timed_stack.rb:77:in `loop'
connection_pool (2.2.0) lib/connection_pool/timed_stack.rb:77:in `block in pop'
connection_pool (2.2.0) lib/connection_pool/timed_stack.rb:76:in `synchronize'
connection_pool (2.2.0) lib/connection_pool/timed_stack.rb:76:in `pop'
connection_pool (2.2.0) lib/connection_pool.rb:89:in `checkout'
connection_pool (2.2.0) lib/connection_pool.rb:61:in `block in with'
connection_pool (2.2.0) lib/connection_pool.rb:60:in `handle_interrupt'
connection_pool (2.2.0) lib/connection_pool.rb:60:in `with'
react-rails (1.9.0) lib/react/server_rendering.rb:16:in `render'
react-rails (1.9.0) lib/react/rails/component_mount.rb:33:in `block in react_component'
actionview (5.0.0.1) lib/action_view/helpers/capture_helper.rb:39:in `block in capture'
actionview (5.0.0.1) lib/action_view/helpers/capture_helper.rb:203:in `with_output_buffer'
actionview (5.0.0.1) lib/action_view/helpers/capture_helper.rb:39:in `capture'
actionview (5.0.0.1) lib/action_view/helpers/tag_helper.rb:107:in `content_tag'
react-rails (1.9.0) lib/react/rails/component_mount.rb:48:in `react_component'
react-rails (1.9.0) lib/react/rails/view_helper.rb:21:in `react_component'
app/views/collections/show.html.erb:4:in `_app_views_collections_show_html_erb___4552859731058566358_70339694036900'
actionview (5.0.0.1) lib/action_view/template.rb:158:in `block in render'
activesupport (5.0.0.1) lib/active_support/notifications.rb:166:in `instrument'
actionview (5.0.0.1) lib/action_view/template.rb:348:in `instrument'`
```

**Comment by matthieua** [comment]
Fixed, it was something related to `react-bootstrap` not importing modules correctly.

**Comment by rmosolgo** [comment]
😌 I had no idea where to start ... thanks for reporting your findings!

**Comment by gambala** [comment]
@matthieua How did you debug it? I got same error, but I don't use react-bootstrap package in my project.
