### ISSUE TITLE
rails errors on long .jsx files

### ISSUE THREAD

**Issue by mcherz** [reactjs/react-rails#622]
Help us help you! Please choose one:
- [X] My app crashes with `react-rails`, so I've included the stack trace and the exact steps which make it crash.
- [ ] My app doesn't crash, but I'm getting unexpected behavior. So, I've described the unexpected behavior and suggested a new behavior.
- [ ] I'm trying to use `react-rails` with another library, but I'm having trouble. I've described my JavaScript management setup (eg, Sprockets, Webpack...), how I'm trying to use this other library, and why it's not working.
- [ ] I have another issue to discuss.

---

(Describe your issue here)

I have a react class that is, at the moment ~2500 lines long. (I know that's a lot--it's running some very complicated operations on a bunch of nested components, and this keeps them all in one place). Some testing has exposed a fun fact: if my monster file is 100,000 characters or fewer, it runs fine. If it's 100,001 characters or longer, it throws the stack trace below, starting with the largely indecipherable "ReferenceError: unknown: console is not defined."

It's not specific to this app. If I shove a 5,000 line comment block into a different, shorter app, I get the same error.

It seems to be specific to React; if I shove a 30,000 line comment block into a vanilla JS file, everything runs fine.

Top of stack trace pasted below.

```
Completed 500 Internal Server Error in 1248ms (ActiveRecord: 6.5ms)

ExecJS::ProgramError - ReferenceError: unknown: console is not defined:
  execjs (2.7.0) lib/execjs/ruby_racer_runtime.rb:98:in `wrap_error'
  execjs (2.7.0) lib/execjs/ruby_racer_runtime.rb:47:in `rescue in block in call'
  execjs (2.7.0) lib/execjs/ruby_racer_runtime.rb:44:in `block in call'
  execjs (2.7.0) lib/execjs/ruby_racer_runtime.rb:75:in `block in lock'
  execjs (2.7.0) lib/execjs/ruby_racer_runtime.rb:73:in `lock'
  execjs (2.7.0) lib/execjs/ruby_racer_runtime.rb:43:in `call'
  babel-transpiler (0.7.0) lib/babel/transpiler.rb:28:in `transform'
  react-rails (1.8.2) lib/react/jsx/babel_transformer.rb:18:in `transform'
  react-rails (1.8.2) lib/react/jsx.rb:21:in `transform'
  react-rails (1.8.2) lib/react/jsx/processor.rb:6:in `call'
  sprockets (3.7.0) lib/sprockets/processor_utils.rb:75:in `call_processor'
  sprockets (3.7.0) lib/sprockets/processor_utils.rb:57:in `block in call_processors'
  sprockets (3.7.0) lib/sprockets/processor_utils.rb:56:in `call_processors'
  sprockets (3.7.0) lib/sprockets/processor_utils.rb:75:in `call_processor'
  sprockets (3.7.0) lib/sprockets/processor_utils.rb:57:in `block in call_processors'
  sprockets (3.7.0) lib/sprockets/processor_utils.rb:56:in `call_processors'
  sprockets (3.7.0) lib/sprockets/loader.rb:134:in `load_from_unloaded'
  sprockets (3.7.0) lib/sprockets/loader.rb:60:in `block in load'
  sprockets (3.7.0) lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
  sprockets (3.7.0) lib/sprockets/loader.rb:44:in `load'
  sprockets (3.7.0) lib/sprockets/cached_environment.rb:20:in `block in initialize'
  sprockets (3.7.0) lib/sprockets/cached_environment.rb:47:in `load'
  sprockets (3.7.0) lib/sprockets/bundle.rb:23:in `block in call'
  sprockets (3.7.0) lib/sprockets/utils.rb:196:in `dfs'
  sprockets (3.7.0) lib/sprockets/bundle.rb:24:in `call'
  sprockets (3.7.0) lib/sprockets/processor_utils.rb:75:in `call_processor'
  sprockets (3.7.0) lib/sprockets/processor_utils.rb:57:in `block in call_processors'
  sprockets (3.7.0) lib/sprockets/processor_utils.rb:56:in `call_processors'
  sprockets (3.7.0) lib/sprockets/loader.rb:134:in `load_from_unloaded'
  sprockets (3.7.0) lib/sprockets/loader.rb:60:in `block in load'
  sprockets (3.7.0) lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
  sprockets (3.7.0) lib/sprockets/loader.rb:44:in `load'
  sprockets (3.7.0) lib/sprockets/cached_environment.rb:20:in `block in initialize'
  sprockets (3.7.0) lib/sprockets/cached_environment.rb:47:in `load'
  sprockets (3.7.0) lib/sprockets/base.rb:66:in `find_asset'
  sprockets (3.7.0) lib/sprockets/base.rb:92:in `[]'
  sprockets-rails (3.1.1) lib/sprockets/rails/helper.rb:338:in `find_asset'
  sprockets-rails (3.1.1) lib/sprockets/rails/helper.rb:330:in `find_debug_asset'
  sprockets-rails (3.1.1) lib/sprockets/rails/helper.rb:212:in `block in lookup_debug_asset'
  sprockets-rails (3.1.1) lib/sprockets/rails/helper.rb:225:in `block in resolve_asset'
  sprockets-rails (3.1.1) lib/sprockets/rails/helper.rb:224:in `resolve_asset'
  sprockets-rails (3.1.1) lib/sprockets/rails/helper.rb:211:in `lookup_debug_asset'
  sprockets-rails (3.1.1) lib/sprockets/rails/helper.rb:124:in `block in javascript_include_tag'
  sprockets-rails (3.1.1) lib/sprockets/rails/helper.rb:123:in `javascript_include_tag'
```

... etc on down.

**Comment by rmosolgo** [comment]
Digging into a couple spots on that call trace 

https://github.com/babel/ruby-babel-transpiler/blob/master/lib/babel/transpiler.rb#L28

https://github.com/rails/execjs/blob/master/lib/execjs/ruby_racer_runtime.rb#L88

Crazy that it's 100_000 chars exactly ... !

**Comment by rmosolgo** [comment]
I was able to replicate this issue without `react-rails`. I loaded an IRB console, created a giant "script", then tried to translate it with babel-transpiler: 

```ruby 
require "therubyracer"

ctx = V8::Context.new
# ... 
script = "[#{Array.new(100_000, 1).join(",")}]"; nil
puts script.length
# => 200001
ctx.eval(script)
# => #<V8::Array:0x007faaa47e4450 @context=#<V8::Context:0x007faaa43c4d48 @conversion=#<V8::Conversion:0x007faaa43c4bb8 @v8_idmap=#<V8::Weak::WeakValueMap:0x007faaa47e4720 @values={697811237=>#<V8::Weak::Ref:0x007faaa47e4428 @ref=#<V8::Array:0x007faaa47e4450 ...>>}>, @ruby_idmap=#<V8::Weak::WeakValueMap:0x007faaa47e4220 @values={70185440453160=>#<V8::Weak::Ref:0x007faaa47e41d0 @ref=#<V8::C::Array:0x007faaa47e4860>>}>>, @access=#<V8::Access:0x007faaa43c4b68>, @timeout=nil, @native=#<V8::C::Context:0x007faaa43c49d8>>, @native=#<V8::C::Array:0x007faaa47e4860>>

require "babel-transpiler"

Babel::Transpiler.transform(script)

 ExecJS::ProgramError: ReferenceError: unknown: console is not defined
	from Function.normalizeOptions ((execjs):6045:9)
	from new CodeGenerator ((execjs):6000:33)
	from Object.module.exports [as default] ((execjs):6462:13)
	from File.generate ((execjs):8838:42)
	from File.transform ((execjs):8667:17)
	from (execjs):13515:19
	from File.wrap ((execjs):8681:16)
	from Pipeline.transform ((execjs):13512:17)
	from /Users/rmosolgo/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/execjs-2.7.0/lib/execjs/ruby_racer_runtime.rb:47:in `rescue in block in call'
	from /Users/rmosolgo/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/execjs-2.7.0/lib/execjs/ruby_racer_runtime.rb:44:in `block in call'
	from /Users/rmosolgo/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/execjs-2.7.0/lib/execjs/ruby_racer_runtime.rb:75:in `block in lock'
	from /Users/rmosolgo/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/execjs-2.7.0/lib/execjs/ruby_racer_runtime.rb:73:in `call'
	from /Users/rmosolgo/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/execjs-2.7.0/lib/execjs/ruby_racer_runtime.rb:73:in `Locker'
	from /Users/rmosolgo/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/execjs-2.7.0/lib/execjs/ruby_racer_runtime.rb:73:in `lock'
	from /Users/rmosolgo/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/execjs-2.7.0/lib/execjs/ruby_racer_runtime.rb:43:in `call'
	from /Users/rmosolgo/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/babel-transpiler-0.7.0/lib/babel/transpiler.rb:28:in `transform'
	from (irb):8
	from /Users/rmosolgo/.rbenv/versions/2.2.2/bin/irb:11:in `<main>'irb(main):009:0>
```

I know it's not helpful but .. I have to punt on this as "upstream"! It looks like `babel-transpiler` is limited in this way (and I don't _know_ of any other way to translate JS from Ruby).

**Comment by mcherz** [comment]
Thanks; I'll raise it with babel and see if I get anywhere.

**Comment by eveevans** [comment]
@mcherz 
Did you find the problem ?

**Comment by erikt9** [comment]
This can be fixed by setting `config.react.jsx_transform_options = { compact: false }` 
(note you may have other settings in there already).

Alternatively, I wrote my own babel transformer which uses a newer babel that no longer has this issue (as I think the bundled babel is version 5 which is several years old now).

**Comment by eveevans** [comment]
Thanks @erikt9  that solve the problem!! 

What I understand is that babel evaluate just the first 500_000 lines of code ? 0_0 
and with `compact 'false'` it will evaluate all (?)

**Comment by erikt9** [comment]
No, what happens is with the compact 'true' option (the default), babel will make a `console.warn` call when over 100_000.  Unfortunately ExecJS environments (where this code is running) don't have a `console` by default, so the babel code crashes.  I think the compact just performs some minification, but you're probably already using another minifier (UglifyJS or Terser) anyways so it doesn't really matter.

**Comment by eveevans** [comment]
Thanks a lot @erikt9, that clarifies me all.
This was a very very weird bug that got me crazy !
