### ISSUE TITLE
tmp/react-rails files not created in WSL install

### ISSUE THREAD

**Issue by l3iodeez** [reactjs/react-rails#673]
Help us help you! Please choose one:

- [x] My app crashes with `react-rails`, so I've included the stack trace and the exact steps which make it crash.
- [ ] My app doesn't crash, but I'm getting unexpected behavior. So, I've described the unexpected behavior and suggested a new behavior.
- [ ] I'm trying to use `react-rails` with another library, but I'm having trouble. I've described my JavaScript management setup (eg, Sprockets, Webpack...), how I'm trying to use this other library, and why it's not working.
- [ ] I have another issue to discuss.

-------
I am trying to use react-rails on Windows-Subsystem-For-Linux (WSL). I have been able to get everything else working, with postgres running on windows and my rails app running under bash on WSL. So far so good. When I attempt to load any page I get the following error "Sprockets::FileNotFound at /
couldn't find file 'react' with type 'application/javascript' "

I was able to determine that the problem lies with the creation of the tmp folder and files within, which have not been created. I saw that some others had similar problems https://github.com/reactjs/react-rails/issues/184, but was not able to resolve my issue. I know I am getting this error becasue the react files do not exist, but I am not sure what to do from here. 

Any help you can offer is much appreciated. 

Stacktrace: 

```
Started GET "/" for 127.0.0.1 at 2017-03-21 21:14:27 -0400
Processing by StaticPagesController#root as HTML
  Rendered static_pages/root.html within layouts/application (0.0ms)
Completed 500 Internal Server Error in 23ms (ActiveRecord: 0.0ms)

Sprockets::FileNotFound - couldn't find file 'react' with type 'application/javascript':
  sprockets (3.5.2) lib/sprockets/directive_processor.rb:182:in `rescue in block in process_directives'
  sprockets (3.5.2) lib/sprockets/directive_processor.rb:179:in `block in process_directives'
  sprockets (3.5.2) lib/sprockets/directive_processor.rb:178:in `process_directives'
  sprockets (3.5.2) lib/sprockets/directive_processor.rb:83:in `_call'
  sprockets (3.5.2) lib/sprockets/directive_processor.rb:68:in `call'
  sprockets (3.5.2) lib/sprockets/processor_utils.rb:75:in `call_processor'
  sprockets (3.5.2) lib/sprockets/processor_utils.rb:57:in `block in call_processors'
  sprockets (3.5.2) lib/sprockets/processor_utils.rb:56:in `call_processors'
  sprockets (3.5.2) lib/sprockets/loader.rb:134:in `load_from_unloaded'
  sprockets (3.5.2) lib/sprockets/loader.rb:60:in `block in load'
  sprockets (3.5.2) lib/sprockets/loader.rb:318:in `fetch_asset_from_dependency_cache'
  sprockets (3.5.2) lib/sprockets/loader.rb:44:in `load'
  sprockets (3.5.2) lib/sprockets/cached_environment.rb:20:in `block in initialize'
  sprockets (3.5.2) lib/sprockets/cached_environment.rb:47:in `load'
  sprockets (3.5.2) lib/sprockets/bundle.rb:23:in `block in call'
  sprockets (3.5.2) lib/sprockets/utils.rb:183:in `dfs'
  sprockets (3.5.2) lib/sprockets/bundle.rb:24:in `call'
  sprockets (3.5.2) lib/sprockets/processor_utils.rb:75:in `call_processor'
  sprockets (3.5.2) lib/sprockets/processor_utils.rb:57:in `block in call_processors'
  sprockets (3.5.2) lib/sprockets/processor_utils.rb:56:in `call_processors'
  sprockets (3.5.2) lib/sprockets/loader.rb:134:in `load_from_unloaded'
  sprockets (3.5.2) lib/sprockets/loader.rb:60:in `block in load'
  sprockets (3.5.2) lib/sprockets/loader.rb:318:in `fetch_asset_from_dependency_cache'
  sprockets (3.5.2) lib/sprockets/loader.rb:44:in `load'
  sprockets (3.5.2) lib/sprockets/cached_environment.rb:20:in `block in initialize'
  sprockets (3.5.2) lib/sprockets/cached_environment.rb:47:in `load'
  sprockets (3.5.2) lib/sprockets/base.rb:66:in `find_asset'
  sprockets (3.5.2) lib/sprockets/base.rb:73:in `find_all_linked_assets'
  sprockets (3.5.2) lib/sprockets/manifest.rb:142:in `block in find'
  sprockets (3.5.2) lib/sprockets/legacy.rb:114:in `block (2 levels) in logical_paths'
  sprockets (3.5.2) lib/sprockets/path_utils.rb:225:in `block in stat_tree'
  sprockets (3.5.2) lib/sprockets/path_utils.rb:209:in `block in stat_directory'
  sprockets (3.5.2) lib/sprockets/path_utils.rb:206:in `stat_directory'
  sprockets (3.5.2) lib/sprockets/path_utils.rb:224:in `stat_tree'
  sprockets (3.5.2) lib/sprockets/legacy.rb:105:in `block in logical_paths'
  sprockets (3.5.2) lib/sprockets/legacy.rb:104:in `logical_paths'
  sprockets (3.5.2) lib/sprockets/manifest.rb:140:in `find'
  sprockets-rails (3.0.4) lib/sprockets/railtie.rb:49:in `precompiled_assets'
  sprockets-rails (3.0.4) lib/sprockets/railtie.rb:34:in `asset_precompiled?'
  sprockets-rails (3.0.4) lib/sprockets/railtie.rb:214:in `block (3 levels) in <class:Railtie>'
  sprockets-rails (3.0.4) lib/sprockets/rails/helper.rb:345:in `precompiled?'
  sprockets-rails (3.0.4) lib/sprockets/rails/helper.rb:349:in `raise_unless_precompiled_asset'
  sprockets-rails (3.0.4) lib/sprockets/rails/helper.rb:334:in `find_debug_asset'
  sprockets-rails (3.0.4) lib/sprockets/rails/helper.rb:216:in `block in lookup_debug_asset'
  sprockets-rails (3.0.4) lib/sprockets/rails/helper.rb:229:in `block in resolve_asset'
  sprockets-rails (3.0.4) lib/sprockets/rails/helper.rb:228:in `resolve_asset'
  sprockets-rails (3.0.4) lib/sprockets/rails/helper.rb:215:in `lookup_debug_asset'
  sprockets-rails (3.0.4) lib/sprockets/rails/helper.rb:157:in `block in stylesheet_link_tag'
  sprockets-rails (3.0.4) lib/sprockets/rails/helper.rb:156:in `stylesheet_link_tag'
  app/views/layouts/application.html.erb:5:in `_app_views_layouts_application_html_erb__2858561672724827760_53651840'
  actionview (4.2.1) lib/action_view/template.rb:145:in `block in render'
  activesupport (4.2.1) lib/active_support/notifications.rb:166:in `instrument'
  actionview (4.2.1) lib/action_view/template.rb:333:in `instrument'
  actionview (4.2.1) lib/action_view/template.rb:143:in `render'
  actionview (4.2.1) lib/action_view/renderer/template_renderer.rb:66:in `render_with_layout'
  actionview (4.2.1) lib/action_view/renderer/template_renderer.rb:52:in `render_template'
  actionview (4.2.1) lib/action_view/renderer/template_renderer.rb:14:in `render'
  actionview (4.2.1) lib/action_view/renderer/renderer.rb:42:in `render_template'
  actionview (4.2.1) lib/action_view/renderer/renderer.rb:23:in `render'
  actionview (4.2.1) lib/action_view/rendering.rb:100:in `_render_template'
  actionpack (4.2.1) lib/action_controller/metal/streaming.rb:217:in `_render_template'
  actionview (4.2.1) lib/action_view/rendering.rb:83:in `render_to_body'
  actionpack (4.2.1) lib/action_controller/metal/rendering.rb:32:in `render_to_body'
  actionpack (4.2.1) lib/action_controller/metal/renderers.rb:37:in `render_to_body'
  actionpack (4.2.1) lib/abstract_controller/rendering.rb:25:in `render'
  actionpack (4.2.1) lib/action_controller/metal/rendering.rb:16:in `render'
  actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
  activesupport (4.2.1) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
  /home/henry/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
  activesupport (4.2.1) lib/active_support/core_ext/benchmark.rb:12:in `ms'
  actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
  actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
  activerecord (4.2.1) lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
  actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:43:in `render'
  actionpack (4.2.1) lib/action_controller/metal/implicit_render.rb:10:in `default_render'
  actionpack (4.2.1) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.2.1) lib/abstract_controller/base.rb:198:in `process_action'
  actionpack (4.2.1) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.2.1) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.2.1) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
  activesupport (4.2.1) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:92:in `_run_callbacks'
  activesupport (4.2.1) lib/active_support/callbacks.rb:776:in `_run_process_action_callbacks'
  activesupport (4.2.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.1) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (4.2.1) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.1) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.2.1) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.2.1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.2.1) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.1) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.1) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.2.1) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.1) lib/action_controller/metal.rb:237:in `block in action'
  actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
  actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:43:in `serve'
  actionpack (4.2.1) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.1) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:819:in `call'
  rack (1.6.4) lib/rack/etag.rb:24:in `call'
  rack (1.6.4) lib/rack/conditionalget.rb:25:in `call'
  rack (1.6.4) lib/rack/head.rb:13:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.2.1) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.2.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:649:in `call'
  activerecord (4.2.1) lib/active_record/migration.rb:378:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:88:in `_run_callbacks'
  activesupport (4.2.1) lib/active_support/callbacks.rb:776:in `_run_call_callbacks'
  activesupport (4.2.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.1) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  web-console (2.3.0) lib/web_console/middleware.rb:28:in `block in call'
  web-console (2.3.0) lib/web_console/middleware.rb:18:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.1) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.1) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.1) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.1) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.1) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/static.rb:113:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.1) lib/rails/engine.rb:518:in `call'
  railties (4.2.1) lib/rails/application.rb:164:in `call'
  rack (1.6.4) lib/rack/content_length.rb:15:in `call'
  puma (3.1.0) lib/puma/configuration.rb:227:in `call'
  puma (3.1.0) lib/puma/server.rb:561:in `handle_request'
  puma (3.1.0) lib/puma/server.rb:406:in `process_client'
  puma (3.1.0) lib/puma/server.rb:271:in `block in run'
  puma (3.1.0) lib/puma/thread_pool.rb:111:in `block in spawn_thread'

```

**Comment by rmosolgo** [comment]
Starting in 1.2.0, we stopped writing files to the tmp directory because of difficulties like this. 

Instead, the rubygem contains _each_ of the possible React.js files in a different directory as `react.js` and we use the [user-provided configuration to choose which directory](https://github.com/reactjs/react-rails/blob/master/lib/react/rails/asset_variant.rb) to add to Sprockets' load path. 

- Which version of react-rails are you on?
- Are you sure you restarted the Rails server after installing the gem? 
- Can you share the output of `puts Rails.application.assets.paths` from a Rails console? You should get a long list of directories and `react-rails` should be among them.

**Comment by rmosolgo** [comment]
Feel free to reopen this with the information I requested above if you'd like help debugging.
