### ISSUE TITLE
Server-Side Rendering Unable to find module

### ISSUE THREAD

**Issue by ysdanielkim** [reactjs/react-rails#701]
Help us help you! Please choose one:

- [x] My app crashes with `react-rails`, so I've included the stack trace and the exact steps which make it crash.

-------

Client-side rendering works fine. However, whenever I try to do server-side rendering, I'm getting the following error:
```
Encountered error "#<ExecJS::ProgramError: ReferenceError: md is not defined>" when prerendering md with {} eval (eval at module.exports ((execjs):24650:19), <anonymous>:1:1) module.exports ((execjs):24650:19) Object.getConstructor ((execjs):28488:19) Object.serverRender ((execjs):24767:31) eval (eval at <anonymous> ((execjs):28528:8), <anonymous>:6:45) eval (eval at <anonymous> ((execjs):28528:8), <anonymous>:18:13) (execjs):28528:8 (execjs):28534:14 global ((execjs):1:102) Object.<anonymous> ((execjs):1:120) 
/Users/danielkim/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/execjs-2.7.0/lib/execjs/external_runtime.rb:39:in `exec' 
/Users/danielkim/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/execjs-2.7.0/lib/execjs/external_runtime.rb:21:in `eval' 
/Users/danielkim/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/react-rails-2.0.2/lib/react/server_rendering/exec_js_renderer.rb:39:in `render_from_parts' 
/Users/danielkim/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/react-rails-2.0.2/lib/react/server_rendering/exec_js_renderer.rb:20:in `render' 
/Users/danielkim/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/react-rails-2.0.2/lib/react/server_rendering/bundle_renderer.rb:40:in `render' 
/Users/danielkim/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/react-rails-2.0.2/lib/react/server_rendering.rb:27:in `block in render' 
...
```

This is `js_code` from `exec_js_renderer.rb:38`
```
(function () {\n            if (typeof console !== \"undefined\" && console.history) {\n  console.history = [];\n}\n\n            var result = this.ReactRailsUJS.serverRender('renderToString', 'md', {});\n            (function (history) {\n  if (history && history.length > 0) {\n    result += '\\n<scr'+'ipt class=\"react-rails-console-replay\">';\n    history.forEach(function (msg) {\n      result += '\\nconsole.' + msg.level + '.apply(console, ' + JSON.stringify(msg.arguments) + ');';\n    });\n    result += '\\n</scr'+'ipt>';\n  }\n})(console.history);\n\n            return result;\n          })()\n
```

```
// app/controllers/home_controller.rb

class HomeController < ApplicationController
  def index
    render component: 'md'
  end
end
```

```
// app/javascript/components/md.jsx

import React, { Component }  from 'react';
import Button from 'react-md/lib/Buttons';

export default class extends Component {
  render() {
    return <Button raised label="Hello, World!" />;
  }
}
```

```
// app/javascript/packs/server_rendering.js

var componentRequireContext = require.context("components", true)
var ReactRailsUJS = require("react_ujs")
ReactRailsUJS.useContext(componentRequireContext)
```

I'm using Rails 5.1.0.rc1. fyi, I had to apply this fix (https://github.com/reactjs/react-rails/issues/695) manually to get things working on 5.1.0.rc1.

**Comment by alkesh26** [comment]
@ysdanielkim Are you still facing this issue? Let's close this one. Feel free to create a new one or reopen this issue.
