### ISSUE TITLE
uninitialized constant React::ServerRendering

### ISSUE THREAD

**Issue by iamdriz** [reactjs/react-rails#804]
In my `application.rb` I have:
~~~
# Settings for the pool of renderers:
config.react.server_renderer_pool_size  ||= 1  # ExecJS doesn't allow more than one on MRI
config.react.server_renderer_timeout    ||= 20 # seconds
config.react.server_renderer = React::ServerRendering::BundleRenderer
config.react.server_renderer_options = {
  files: ["server_rendering.js"],       # files to load for prerendering
  replay_console: true,                 # if true, console.* will be replayed client-side
}
# Changing files matching these dirs/exts will cause the server renderer to reload:
config.react.server_renderer_extensions = ["jsx", "js"]
config.react.server_renderer_directories = ["/app/assets/javascripts", "/app/javascripts/"]
~~~
However when I try and start the Rails server I get the error:
~~~
/Users/cameron.drysdale/Projects/accounts-react-rails-jsx/config/application.rb:30:in `<class:Application>': uninitialized constant React::ServerRendering (NameError)
        from /Users/cameron.drysdale/Projects/accounts-react-rails-jsx/config/application.rb:10:in `<module:Accounts>'
        from /Users/cameron.drysdale/Projects/accounts-react-rails-jsx/config/application.rb:9:in `<top (required)>'
        from /Users/cameron.drysdale/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:78:in `require'
        from /Users/cameron.drysdale/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:78:in `block in server'
        from /Users/cameron.drysdale/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:75:in `tap'
        from /Users/cameron.drysdale/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:75:in `server'
        from /Users/cameron.drysdale/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from /Users/cameron.drysdale/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/railties-4.2.1/lib/rails/commands.rb:17:in `<top (required)>'
        from /Users/cameron.drysdale/Projects/accounts-react-rails-jsx/bin/rails:8:in `require'
        from /Users/cameron.drysdale/Projects/accounts-react-rails-jsx/bin/rails:8:in `<top (required)>'
        from /Users/cameron.drysdale/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/spring-1.3.6/lib/spring/client/rails.rb:28:in `load'
        from /Users/cameron.drysdale/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/spring-1.3.6/lib/spring/client/rails.rb:28:in `call'
        from /Users/cameron.drysdale/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/spring-1.3.6/lib/spring/client/command.rb:7:in `call'
        from /Users/cameron.drysdale/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/spring-1.3.6/lib/spring/client.rb:26:in `run'
        from /Users/cameron.drysdale/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/spring-1.3.6/bin/spring:48:in `<top (required)>'
        from /Users/cameron.drysdale/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/spring-1.3.6/lib/spring/binstub.rb:11:in `load'
        from /Users/cameron.drysdale/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/spring-1.3.6/lib/spring/binstub.rb:11:in `<top (required)>'
        from /Users/cameron.drysdale/.rbenv/versions/2.1.10/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Users/cameron.drysdale/.rbenv/versions/2.1.10/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Users/cameron.drysdale/Projects/accounts-react-rails-jsx/bin/spring:13:in `<top (required)>'
        from bin/rails:3:in `load'
        from bin/rails:3:in `<main>'
~~~
If I comment out the line: `config.react.server_renderer = React::ServerRendering::BundleRenderer` then I can start the server, but then the rendering fails because it can't find referenced files in my `server_rendering.js` file... even though this file is compiled by the asset pipeline with: `Rails.application.config.assets.precompile += %w( server_rendering.js )` and the `server_rendering.js` file contains:
~~~
//= require react
//= require react_ujs
//= require react-server
//= require components
//= require utils
~~~

**Comment by BookOfGreg** [comment]
Hi @iamdriz , Sorry I didn't get to this one before it was closed. Did you solve the issue or was it not with the branch? Future visitors to this thread may be interested in your thoughts.
Thank you. :)

**Comment by iamdriz** [comment]
@BookOfGreg Hi sorry, yeah for some reason I had the version set as 1.0 in the Gemfile so the Server Rendering wasn't even in the gem! So specifying 2.3.0 fixed it, however now I'm getting an issue with `window` not being referenced even though it's not used in any of my code or dependancies.

**Comment by BookOfGreg** [comment]
Interesting, could you expand on the `window` issue you are having, perhaps with another open issue if you can make a basic app/reproducible list of steps. Thank you :)
