### ISSUE TITLE
uninitialized constant React::Rails::Application (NameError) due to lib/react.js conflict

### ISSUE THREAD

**Issue by vladi160** [reactjs/react-rails#831]
With new created Rails app (latest version) on Windows 10 and installed gems 'webpacker' and `react-rails`:
`gem 'webpacker'`
`gem 'react-rails'`
I am getting this error, when I try to start the server with `rails s`:
```
> 
C:/Users//Desktop/react/config/application.rb:10:in `<module:React>': uninitialized cons
tant React::Rails::Application (NameError)
        from C:/Users//Desktop/react/config/application.rb:9:in `<top (required)>'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/railties-5.1.4/lib/rails/commands/server/server
_command.rb:133:in `require'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/railties-5.1.4/lib/rails/commands/server/server
_command.rb:133:in `block in perform'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/railties-5.1.4/lib/rails/commands/server/server
_command.rb:130:in `tap'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/railties-5.1.4/lib/rails/commands/server/server
_command.rb:130:in `perform'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invo
ke_command'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/railties-5.1.4/lib/rails/command/base.rb:63:in
`perform'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/railties-5.1.4/lib/rails/command.rb:44:in `invo
ke'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/railties-5.1.4/lib/rails/commands.rb:16:in `<to
p (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'
```

**Comment by BookOfGreg** [comment]
Don't want to call your app React, it's going to conflict with https://github.com/reactjs/react-rails/blob/master/lib/react.rb
Arguably we shouldn't use the term React either.

Can you generate a new app with a different name and see if that solves this issue?

**Comment by vladi160** [comment]
Hi, this was the problem.
